openapi: 3.0.3
info:
  title: Swagger Operador Logístico - OpenAPI 3.0
  description: |-
    API Backend que permite el alta de órdenes de envíos, la asignación de repartidores para la entrega de productos a destinatarios y el registro de entregas de órdenes de envíos como así la notificación vía Webhook de las entregas realizadas.
  version: 1.0.11
servers:
  - url: https://operador.swagger.io/api/v1 
tags:
  - name: ordenes_envio
    description: Info sobre ordenes de envio
  - name: repartidores
    description: Info sobre repartidores de las ordenes
paths:
  /ordenes_envio:
    post:
      tags:
        - ordenes_envio
      summary: Crear una nueva orden de envio
      description: Crear orden de envio
      operationId: addOrden
      requestBody:
        description: Crear una nueva orden de envio
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Orden'
          application/xml:
            schema:
              $ref: '#/components/schemas/Orden'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Orden'
        required: true
      responses:
        '201':
          description: La orden fue creada correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Orden'
        '400':
          description: Formato inválido
        '401':
          description: Error de autenticación
        '500':
          description: Error de servidor
      security:
        - operador_auth:
            - write:orden
            - read:orden
  /ordenes_envio/{ordenId}:
    get:
      tags:
        - ordenes_envio
      summary: Encontrar un orden por su ID
      description: Devuelve una unica orden 
      operationId: getOrdenById
      parameters:
        - name: ordenId
          in: path
          description: ID de la orden de envio
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Ejecución correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Orden'
        '400':
          description: Formato inválido
        '401':
          description: Error de autenticación
        '404':
          description: Orden no encontrada
        '500':
          description: Error de servidor
      security:
        - api_key: []
        - operador_auth:
            - write:orden
            - read:orden
  /ordenes_envio/{ordenId}/repartidor:
    post:
      tags:
        - ordenes_envio
      summary: Asignar repartidor a orden
      description: Asignar repartidor a orden de envio
      operationId: addRepartidorOrden
      parameters:
        - name: ordenId
          in: path
          description: ID de la orden de envio
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Asignar repartidor disponible a orden de envio
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Repartidor'
          application/xml:
            schema:
              $ref: '#/components/schemas/Repartidor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Repartidor'
        required: true
      responses:
        '200':
          description: Ejecución correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Orden'
        '400':
          description: Formato inválido
        '401':
          description: Error de autenticación
        '404':
          description: Orden no encontrada
        '500':
          description: Error de servidor
      security:
        - operador_auth:
            - write:orden
            - read:orden
  /ordenes_envio/{ordenId}/entrega:
    post:
      tags:
        - ordenes_envio
      summary: Registrar entrega de una orden
      description: Registrar entrega de una orden de envio
      operationId: addEntregaOrden
      parameters:
        - name: ordenId
          in: path
          description: ID de la orden de envio
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        description: Registrar entrega de una orden de envio
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Entrega'
          application/xml:
            schema:
              $ref: '#/components/schemas/Entrega'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Entrega'
        required: true
      responses:
        '200':
          description: Ejecución correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Orden'
        '400':
          description: Formato inválido
        '401':
          description: Error de autenticación
        '404':
          description: Orden no encontrada
        '500':
          description: Error de servidor
      security:
        - operador_auth:
            - write:orden
            - read:orden
  /repartidores:
    post:
      tags:
        - repartidores
      summary: Crear un nuevo repartidor
      description: Crear repartidor
      operationId: addRepartidor
      requestBody:
        description: Crear un nuevo repartidor
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Repartidor'
          application/xml:
            schema:
              $ref: '#/components/schemas/Repartidor'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Repartidor'
        required: true
      responses:
        '201':
          description: Repartidor creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Orden'
        '400':
          description: Formato inválido
        '401':
          description: Error de autenticación
        '500':
          description: Error de servidor
      security:
        - operador_auth:
            - write:orden
            - read:orden
  /repartidores/{repartidorId}:
    get:
      tags:
        - repartidores
      summary: Encontrar repartidor por su ID
      description: Devuelve un unico repartidor
      operationId: getRepartidorById
      parameters:
        - name: repartidorId
          in: path
          description: ID del repartidor
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Ejecución correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Orden'
        '400':
          description: Formato inválido
        '401':
          description: Error de autenticación
        '404':
          description: Repartidor no encontrado
        '500':
          description: Error de servidor
      security:
        - api_key: []
        - operador_auth:
            - write:orden
            - read:orden
    delete:
      tags:
        - repartidores
      summary: Elimina un repartidor
      description: Elimina un repartidor
      operationId: deleteRepartidor
      parameters:
        - name: repartidorId
          in: path
          description: Id del repartidor a eliminar 
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '204':
          description: Ejecución correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Orden'          
            application/xml:
              schema:
                $ref: '#/components/schemas/Orden'
        '400':
          description: Formato inválido
        '401':
          description: Error de autenticación
        '404':
          description: Repartidor no encontrado
        '500':
          description: Error de servidor
      security:
        - operador_auth:
            - write:orden
            - read:orden

components:
  schemas:
    Orden:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        envioId:
          type: integer
          format: int64
          example: 1987
        fechaEnvio:
          type: string
          format: date-time
        estado:
          type: string
          description: Estado envio
          example: creado
          enum:
            - creado
            - enTransito
            - entregado
        dirOrigen:
          type: array
          xml:
            name: direccion
            wrapped: true
          items:
            $ref: '#/components/schemas/Direccion'
        dirDestino:
          type: array
          xml:
            name: direccion
            wrapped: true
          items:
            $ref: '#/components/schemas/Direccion'
        compradorId:
          type: integer
          format: int64
          example: 204
        productoId:
          type: integer
          format: int64
          example: 2209
        repartidorId:
          type: integer
          format: int64
          example: 2209
      xml:
        name: orden
    Entrega:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1982093
      xml:
        name: entrega
    Repartidor:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 100000
        username:
          type: string
          example: pepeDias
        firstName:
          type: string
          example: Pedro
        lastName:
          type: string
          example: Dias
        email:
          type: string
          example: pdias@email.com
      xml:
        name: repartidor
    Direccion:
      type: object
      properties:
        calle:
          type: string
          example: Ilia 377
        ciudad:
          type: string
          example: Cordoba
        provincia:
          type: string
          example: Cordoba
        zip:
          type: string
          example: '5000'
      xml:
        name: direccion
    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'
        
  requestBodies:
    Oreden:
      description: Orden Object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Orden'
        application/xml:
          schema:
            $ref: '#/components/schemas/Orden'

  securitySchemes:
    operador_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://aDEFINIR.swagger.io/oauth/authorize
          scopes:
            write:orden: modificar ordenes
            read:orden: leer ordenes
    api_key:
      type: apiKey
      name: api_key
      in: header